name: readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6/12 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
        with:
          template: "templates/README.tpl"
          writeTo: "README.md"

      - name: Git commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          if git commit -m "Auto update README"; then
            git push
          fi
